image:
  repository: matanm66/weather-app
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2  # Possibly more for production

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# Environment variables for the app
environment:
  OPENWEATHER_API_KEY: ""

ingress:
  enabled: true

  # For EKS + ALB Ingress Controller:
  className: "alb"  

  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/load-balancer-attributes: "routing.http2.enabled=true"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'

  hosts:
    - host: weatherapp.example.com  # or a placeholder; you can override or use ALB DNS
      paths:
        - path: /
          pathType: Prefix

  tls: []
