# The container image to use
image:
  repository: matanm66/weather-app
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

# Basic service configuration
service:
  type: ClusterIP
  port: 80

# Default resource requests/limits (adjust as needed)
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# Environment variables
environment:
  OPENWEATHER_API_KEY: ""

# Ingress-related settings
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: weather-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
